services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/templates
    networks:
      - manablox-network

  mongodb:
    image: mongo:7.0
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - manablox-network

  manablox-admin:
    image: node:20
    hostname: manablox-admin
    ports:
      - 24678:24678
    volumes:
      - ./packages/admin:/app
    working_dir: /app
    env_file:
      - ./packages/admin/.env
    networks:
      - manablox-network
    command: sh -c 'yarn && exec yarn dev'

  manablox-server:
    image: node:20
    hostname: manablox-server
    volumes:
      - ./packages/server:/app
    working_dir: /app
    env_file:
      - ./packages/server/.env
    depends_on:
      - mongodb
    networks:
      - manablox-network
    command: sh -c 'yarn && exec yarn start:dev manablox'

networks:
  manablox-network:
    driver: bridge
