name: Release production packages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Create release
        uses: cycjimmy/semantic-release-action@v3
        id: create-release
        with:
          working_directory: ./packages/admin
          extra_plugins: |
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      published: ${{ steps.create-release.outputs.new_release_published }}
      version: ${{ steps.create-release.outputs.new_release_version }}
      major: ${{ steps.create-release.outputs.new_release_major_version }}
      minor: ${{ steps.create-release.outputs.new_release_minor_version }}
      patch: ${{ steps.create-release.outputs.new_release_patch_version }}
      head: ${{ steps.create-release.outputs.new_release_git_head }}
      tag: ${{ steps.create-release.outputs.new_release_git_tag }}
      channel: ${{ steps.create-release.outputs.new_release_channel }}
      notes: ${{ steps.create-release.outputs.new_release_notes }}

  push-docker-images:
    name: Create docker images
    needs: release
    runs-on: ubuntu-latest
    environment: ${{ needs.release.outputs.channel }}
    if: ${{ !failure() && !cancelled() && needs.release.outputs.published == 'true' }}
    strategy:
      matrix:
        service:
          - admin
          - manablox_io-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.head }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-${{ matrix.service }}
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=${{ needs.release.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./packages/${{ matrix.service }}
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
